### ISSUE TITLE
MultiPCA tensor product

### ISSUE THREAD

**Issue by lnacquaroli** [caseykneale/ChemometricsTools.jl#11]
Hi there, sorry to bother again.

I have been snooping around the `MultiPCA` algorithm you used since before I found your library I was using drEEM from Bro et al. in Matlab.

I noticed the tensor product line
https://github.com/caseykneale/ChemometricsTools.jl/blob/61c1f6724980329ed0fa27b03896e68c73a4f844/src/MultiWay.jl#L111

Tensors operations are quite developed in `julia` so far, in case you want to check them out:
[https://github.com/Jutho/TensorOperations.jl](https://github.com/Jutho/TensorOperations.jl)
[https://github.com/KristofferC/Tensors.jl](https://github.com/KristofferC/Tensors.jl)
[https://github.com/ITensor/ITensors.jl](https://github.com/ITensor/ITensors.jl)

I confess I have not done any test on this, just to let you know for efficiency comparison in the future and to make use of the packages developed here.

**Comment by caseykneale** [comment]
Thanks for the heads up. When I first wrote this the exact tensor product I was performing there wasn't a direct operation I think. I tried doing it via the kronecker product onboard with julia and it exploded in memory for real data.

I forget the name of that specific product maybe there are other libraries out there (now) doing this sort of thing adequately.

**Comment by caseykneale** [comment]
Also let's leave this issue open - when I get more time I'd like to invest in the multiway algorithms. I have just been swamped.

**Comment by lnacquaroli** [comment]
Looking forward for the MultiwayPLS :)

**Comment by caseykneale** [comment]
I wrote that using Rasmus Bro's code (its on their website) years ago. I didn't like the way I structured it so when I do go for it this time around it'll be a lot more generic. I could probably spin up a version in an afternoon. The tricky part is getting the time! Maybe this weekend? No promises though.

**Comment by caseykneale** [comment]
Do you rely on multiway PLS right now? If so maybe the near future would be a good way to get some user feedback.

**Comment by lnacquaroli** [comment]
Not at the moment , I am not in a rush for it. I did use it a month ago...

**Comment by caseykneale** [comment]
Garauntee there are some bugs but check master for an effort at MPLS

https://caseykneale.github.io/ChemometricsTools.jl/dev/man/MultiWay/

**Comment by lnacquaroli** [comment]
Sorry I did not have time to test it. I will follow up on a new issue if I ever have to. Thanks!
