### ISSUE TITLE
Cutting v0.4.4 Release

### ISSUE THREAD

**Issue by caseykneale** [caseykneale/ChemometricsTools.jl#2]
Enough serious bugs were fixed that this warrants a new release. Also some general features were added.

edit removed cmd to add to registry made new issue

**Comment by nkottary** [comment]
Note that you need to quote the register() bit, Ex: `register()`. I am going to remove this requirement in the actual deployment of Registrator. I understand that this is annoying.

**Comment by caseykneale** [comment]
thanks for that, I made a new "issue" and closed this one with the register() call in single quotes given by the following character: ` . It's not annoying to me I just didn't know :)

**Comment by caseykneale** [comment]
@nkottary Is the issue possibly that JuliaRegistrator has not accepted me as a collaborator yet?

**Comment by caseykneale** [comment]
@nkottary I figured it out. I had to make a new comment or whatever so the server could recognize the request. Just had to read your code, thanks for your help!

**Comment by nkottary** [comment]
Great! The instructions are here: https://juliaregistrator.github.io. There is no need to add JuliaRegistrator as a collaborator. Its just that you need to be a collaborator on the repo that you want to register. Owners count as collaborators.
